### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by raphaelsander** [raphaelsander/Bitcoin-Farm#3]
Logs:

```python
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x75649760>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='blockchain.info', port=443): Max retries exceeded with url: /balance?active=19FdMbrLMc62uBkwzHRPxRFhpzHrVRkEkW%7C1eHFuJQWZPPWYfyoE7qkn8XF5Ya1SwCUc%7C19rP1pkaAmJzak5meLBkYvzhvqoW4qX9rj%7C1HzZs1hqBYQuGKY88i4kVKpnZNqwxVWGK7%7C1Q1vUbiCE9zjwNKhREpznEBgMrkKERSH9m%7C1PzYqLcqihjM4rKJafFu2YPBZCbdd5Lzr5%7C1AHzh9SVCXTXc8b5kLQrTy4nvQ41HapfHi%7C17VsCkJVDDksMqkNxqGztrbPCBPKiS2Vwm%7C1FmDkvk2ycwVup2oUVv2phy5ngbrNNF1T%7C12kdMfAYuBYx1gUFFHQBckAdgWpTaTjzr5%7C1Hj23YP7pbZdrMBiGuAHMCMjjGgzYs4oQb%7C1MFXB49zcX6dyQtDJq3uXuGH37DZHRCUiJ%7C1DuBWPbpk7KxXr811VBqviTqxGvuqr1M82%7C1KLUnKh3ivfQeazz4a1bFBkQZBbpoRxNZL%7C1GFf8XKywwj62hH7eGZbfRs285qRdKAZJP%7C1FZx7NLzEJmZhuwAhiaxEW9ViKpiXC3Vng%7C167jYvK5nj9kGdQ4GCVvM2M7TRxHHbK7Nr%7C1KKmRTB9taJ3m3MiifvK5jUM6j7TTAtJ5E%7C137tB9aRNyEoTS3btz4fSrCmUpjMQdp2M4%7C1PcAmgDQzYMe3i1Y1w2Bi5BxibzY35iMXc%7C185B7X3CriBYTZSjZaAeAQygjLqowECbTi%7C13PC5DH1Ej8QjgAuL8gTQkgESZNXwcbFz1%7C1FZqCJx6yYDrxptXuzNaEgcRoDNQRLxeVs%7C1MSfcm3e7NXWSMydviXWivieFcpnBtZ5VG%7C1F7nHFnWcgCJ6GqWfz1ktxkoH91ZyaavAE%7C17RhnCMyozfa6qLeXY92z7ETD4w44k8Tmv%7C1633gjkz2dkeRtnKcNkfqDuX23i16WuhHU%7C1EeBo25jcJ31eV6cVYTwDLmg4cZxBiza2a%7C1Hvg7PdycudK6KyLPs7SAyUXpyFjuV3boK%7C1JyTTnhCpqzHo5mnH3AGwCpeodS74GZX2Z%7C1N1XE3ZZ2idiJ9A9wX8QhjYYu7ENBitjJS%7C1NNiuG5ZvFMUEDZCVbpgUah8U1FJLmkAvW%7C17nkRRDo8xUJwtmSrvjD32JVzaJj6UdRY%7C17zWQLn6yj3YnBzwikiuHB5tX1BmGN6y5S%7C15N4kVgg6Ryjz5umvxZ8MMTkXti687DxRX%7C19wUWMwT1npvgpW1pUUT7MQvabwG7qr534%7C17orohE28kC29wykSpYgM5PX68dnd8GJmc%7C17UPUj8wsbHRa3SbQkKHYL5kbbBTpa9vRe%7C1K4oKhMumxxSyD9i2oha47GtkrABwPYEm%7C1KZLsA9bnQoHaqDB61WL2EBAN5TeJusbir%7C1Mh4rvB3yWoey1GEDW3N3VxVtxwWeZZKc9%7C1DZncFczwxJ8neijwHYdQDa73W52B7L2X%7C1MvgrQzrLvVitbJkGVurZrVcwVjvNTRRC2%7C145taf3k5Zqbpqaeny4yyekw7HzDthgB1V%7C1Pt1pdaVPeMcCRdMKPZjnHhvSqq4oj6XB2%7C1AJVU25wiUuNpTXK9u5d9jsLMMoJxLcVgj%7C17RfwG4DVcephVkmWbTUifn15K9wcXPXje%7C1J9PRrEXw7NDiUi82UFpUaf5DhrLP4v4GW%7C18ENzq5fLXKnCLscYMT173QP52mTFL2HdE%7C1Hf2wt4JnCGAMmqQef2L8tTPA4KAQ5cjqs%7C13HQs2iUCwzjcLetayqpKZsjN5q7gu3hKb%7C1BSEC85mycdN8bmYwVKRWVFxDKtJa6ubmN%7C179gpLhiKWRmRdErKjsUgSRfXkviHjw5Ps%7C1LVmdXvqHVid81yJDKqHwHNcxMHp6ZaY89%7C1GorEGcVyuZ56wwbNFks8nZibqhtrUSAqt%7C1DbwvzxV21BVEDvBuFk5V3qE9s4gP1WUBs%7C1J8ZwQ1nWqcstkhuojNtJAuqeNN2GWmPgJ%7C1S7nGFGn3fgPr2HKHT81k2SNz2sLRPWuL%7C1PXaphG9Epe9C4WnfmPkbV2n3yqeSsQYC%7C14N9BrEQD2ucQ6RgzP92ioTQzxS1RwVY5p%7C14g6Q2QVdTQ2iNPdfNYYM1aU1Gr6boT8tn%7C1MuQQwa8RubejaiaBs2CtM2S3HwjNR3iiG%7C1FMjja2SXKo5WykRreVt76YJR5Jc2f8Q4z%7C14YFEuQJK9SDRUkDkQgmaD37aEjZxLAQhV%7C1BnUvRM31Q14cxRCFtJR37ZV92ZghQsMMB%7C1CC1JvwBDmJjnQdiSTFmBvcJwSMpSWfgq5%7C16ham7fqty2ArEYvjm9XUnRgQiLFhMfPSe%7C1NfhjFg9Yc4JxDU2kGX3kqxiNcfgtXjeDQ%7C1CBumw4oi3tNJgddfFghzAQv3Fv4QS2LvP%7C1JXc3hyMKDz3dbAAcVptqeY7LuwbAtQiL3%7C18C7QPUWDLT6wHhkeecfRUY3ccepTxy1ZQ%7C1N7VPACFfgMNQN8K1YD4DMVzLqo7RyaAq4%7C1LuNg3HhbwmJ5RP7VxPT9XrDJpYuGvxf7y%7C149adyrYTtgw7377uB3TJkuLZ8BfKzZdcP%7C1FC7fFo9a2rysxFympAGR6C6s4MY7CXAtA%7C1LMh5PUVG4yEXCs7tFs9UXceS6Umbdg54y%7C13JQxeQ5jmpSQ6EjznS3MFv1NzxJ5RFbKA%7C13ExP8mLdwFf3xzZ7NzyCtxkwgUdrnsU34%7C13TbNTLpz3ak7r7CdzMoFDVn31ymXfSw7U%7C1FLvpkUaUaizf6dzqbwAwK9PAVZocL2sxP%7C1JDN7fLTZBdjs4cgmBRWfchdmNDyh93Doh%7C1ABrpgsSAzpHpv5qZng3Nrdcf4a3LUQoet%7C14ipAEtXgqmnsMUj6F2RjK7K7YtVPjtCKe%7C1BafYqjB1HcHcdf5qgoQmMr2GzpqEqG2QA%7C1Bm3LzUKSC5JNTmWqa5LMxqekd4AGMjRmm%7C14Vh89KneTkaXxN6UhvLPRtLQScWQgKqEy%7C1GpNFqpP9j8BfjKYqTfbY8HkWWW5Ns6PRs%7C1CQJZm1RKHCKrg979WPPZUQdtpJeCJXJV2%7C1HyuG8gSC5fCutydsmZ5J5xcR9XYbBuv1r%7C1EafsFtngMQVfTvMnqeDKAREs94dKiAE6c%7C16iZQU1xW6eciY5PykDsvYHad39GH31r13%7C18XfusX9aAMYqmiW1NKuDzuLy2RbV1pux7%7C1MTnrEcPbPG93Pg3CSze6rNvzLkMRH77N9%7C1BmrrnwfNT1t496uyB7ppyVuiLrMX3PwxW%7C1RJsVu8NgjuagUgdzY3NkVBfuPvG5P5Ed%7C16Wc9QcYNRpmzGjAFBd6RFpFainRXByhqU%7C17wKJH6vaPCrAU1N1Uc3SiMSD9XNUqaLeb%7C18y4ed3uBDYqLwrotHBm3DYpM6dbhJUjsH%7C1MgFzNEF6GGTeCZzhvc4Zh1kCTrtHNTJZX%7C1PaoyxW8bUj25pAweDmMhBvoibLT2XjdMe%7C1L7uE74R8ooLJ26pVhXBUfbUPx7s4YGsnC%7C1PimqhZ1jnCUX36z8iQvBY5ukt1HGomgRj%7C16sSbuCVC1SmWnmo7eMGzzL8WTDmXpLZ5D%7C1fbsA53gXvHNCs2op6Cqih815uUjTwqvs%7C1Fheg4A3GWyA3cJUSK1iPbWQbQ22BmcsJe%7C18UwJMqZZ9jMKKqenjLU36HxkYCDxzhKc%7C1CDKvmwVtJpzNvD72YSEspvdUr7fUc8WcS%7C1Pxw1w1FJuoBrfLo6QFwA9LAQxerTUHj18%7C1BsPMAgBbhot1paQc4WiKkiHfyz2DEXZZN%7C1F1DbdbumRSrXoRUhMy7Pcjsf9MxNjYEj8%7C1Kx5BurqWd4GigzPqMJuZrb6Z52qx3E4gk%7C137NDACMuXzKa6itmaua6y6qc3c4NWgFUK%7C1G7nzUmH2wBqc7Py8HgtwPUn7kbeRWoR24%7C1N7xzt4GbSrbUKAFaCi7VKNGxmpb8g7Pwf%7C1JutDz3BP9Xi24SSJzgxW2hE7AR2mXL6vD%7C18CjAAXAFcBbJJqou9niS7uCr9bbQu2BSm%7C1K7Fts1W7V95MVAfgXRDmj98Aa1ZRAw8AU%7C1EFLEy4F5388bvUn6QWvgPnE5GrWVK2ef%7C1nZjd3R4rHAXdiptnPtLdeJdAdfp34RCb%7C1CAeqTj6zPqrPptEjcmtXjv2S9z5TtEbji%7C1HdVbXrsMzPw86ECsikwJPSofNJfrSU2eh%7C16F9GoBun9VrF2Qcvo1trzLRn7nMtdhUQN%7C12yp1d6UgPRDkz1i1BfugpZzBoKd9DCnX7%7C1EBngT4auPkvVebydgHr3B65NEKDqu4xWL%7C174kgguY1Fzm6pZS81gwQdWvfAMfDPcWLT%7C18njhypvU7qPoDEmzk87EDmJKEMunCmjQw%7C1PavTcuJzrtSgAoxrz1PcjSWGk4Z4nsreA%7C1ML8rws13EmvsapoKYCowSHuqz4kYtTeWH (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x75649760>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/src/app/bitcoin_farm_multithread.py", line 77, in run
    req2 = requests.get(url)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='blockchain.info', port=443): Max retries exceeded with url: /balance?active=19FdMbrLMc62uBkwzHRPxRFhpzHrVRkEkW%7C1eHFuJQWZPPWYfyoE7qkn8XF5Ya1SwCUc%7C19rP1pkaAmJzak5meLBkYvzhvqoW4qX9rj%7C1HzZs1hqBYQuGKY88i4kVKpnZNqwxVWGK7%7C1Q1vUbiCE9zjwNKhREpznEBgMrkKERSH9m%7C1PzYqLcqihjM4rKJafFu2YPBZCbdd5Lzr5%7C1AHzh9SVCXTXc8b5kLQrTy4nvQ41HapfHi%7C17VsCkJVDDksMqkNxqGztrbPCBPKiS2Vwm%7C1FmDkvk2ycwVup2oUVv2phy5ngbrNNF1T%7C12kdMfAYuBYx1gUFFHQBckAdgWpTaTjzr5%7C1Hj23YP7pbZdrMBiGuAHMCMjjGgzYs4oQb%7C1MFXB49zcX6dyQtDJq3uXuGH37DZHRCUiJ%7C1DuBWPbpk7KxXr811VBqviTqxGvuqr1M82%7C1KLUnKh3ivfQeazz4a1bFBkQZBbpoRxNZL%7C1GFf8XKywwj62hH7eGZbfRs285qRdKAZJP%7C1FZx7NLzEJmZhuwAhiaxEW9ViKpiXC3Vng%7C167jYvK5nj9kGdQ4GCVvM2M7TRxHHbK7Nr%7C1KKmRTB9taJ3m3MiifvK5jUM6j7TTAtJ5E%7C137tB9aRNyEoTS3btz4fSrCmUpjMQdp2M4%7C1PcAmgDQzYMe3i1Y1w2Bi5BxibzY35iMXc%7C185B7X3CriBYTZSjZaAeAQygjLqowECbTi%7C13PC5DH1Ej8QjgAuL8gTQkgESZNXwcbFz1%7C1FZqCJx6yYDrxptXuzNaEgcRoDNQRLxeVs%7C1MSfcm3e7NXWSMydviXWivieFcpnBtZ5VG%7C1F7nHFnWcgCJ6GqWfz1ktxkoH91ZyaavAE%7C17RhnCMyozfa6qLeXY92z7ETD4w44k8Tmv%7C1633gjkz2dkeRtnKcNkfqDuX23i16WuhHU%7C1EeBo25jcJ31eV6cVYTwDLmg4cZxBiza2a%7C1Hvg7PdycudK6KyLPs7SAyUXpyFjuV3boK%7C1JyTTnhCpqzHo5mnH3AGwCpeodS74GZX2Z%7C1N1XE3ZZ2idiJ9A9wX8QhjYYu7ENBitjJS%7C1NNiuG5ZvFMUEDZCVbpgUah8U1FJLmkAvW%7C17nkRRDo8xUJwtmSrvjD32JVzaJj6UdRY%7C17zWQLn6yj3YnBzwikiuHB5tX1BmGN6y5S%7C15N4kVgg6Ryjz5umvxZ8MMTkXti687DxRX%7C19wUWMwT1npvgpW1pUUT7MQvabwG7qr534%7C17orohE28kC29wykSpYgM5PX68dnd8GJmc%7C17UPUj8wsbHRa3SbQkKHYL5kbbBTpa9vRe%7C1K4oKhMumxxSyD9i2oha47GtkrABwPYEm%7C1KZLsA9bnQoHaqDB61WL2EBAN5TeJusbir%7C1Mh4rvB3yWoey1GEDW3N3VxVtxwWeZZKc9%7C1DZncFczwxJ8neijwHYdQDa73W52B7L2X%7C1MvgrQzrLvVitbJkGVurZrVcwVjvNTRRC2%7C145taf3k5Zqbpqaeny4yyekw7HzDthgB1V%7C1Pt1pdaVPeMcCRdMKPZjnHhvSqq4oj6XB2%7C1AJVU25wiUuNpTXK9u5d9jsLMMoJxLcVgj%7C17RfwG4DVcephVkmWbTUifn15K9wcXPXje%7C1J9PRrEXw7NDiUi82UFpUaf5DhrLP4v4GW%7C18ENzq5fLXKnCLscYMT173QP52mTFL2HdE%7C1Hf2wt4JnCGAMmqQef2L8tTPA4KAQ5cjqs%7C13HQs2iUCwzjcLetayqpKZsjN5q7gu3hKb%7C1BSEC85mycdN8bmYwVKRWVFxDKtJa6ubmN%7C179gpLhiKWRmRdErKjsUgSRfXkviHjw5Ps%7C1LVmdXvqHVid81yJDKqHwHNcxMHp6ZaY89%7C1GorEGcVyuZ56wwbNFks8nZibqhtrUSAqt%7C1DbwvzxV21BVEDvBuFk5V3qE9s4gP1WUBs%7C1J8ZwQ1nWqcstkhuojNtJAuqeNN2GWmPgJ%7C1S7nGFGn3fgPr2HKHT81k2SNz2sLRPWuL%7C1PXaphG9Epe9C4WnfmPkbV2n3yqeSsQYC%7C14N9BrEQD2ucQ6RgzP92ioTQzxS1RwVY5p%7C14g6Q2QVdTQ2iNPdfNYYM1aU1Gr6boT8tn%7C1MuQQwa8RubejaiaBs2CtM2S3HwjNR3iiG%7C1FMjja2SXKo5WykRreVt76YJR5Jc2f8Q4z%7C14YFEuQJK9SDRUkDkQgmaD37aEjZxLAQhV%7C1BnUvRM31Q14cxRCFtJR37ZV92ZghQsMMB%7C1CC1JvwBDmJjnQdiSTFmBvcJwSMpSWfgq5%7C16ham7fqty2ArEYvjm9XUnRgQiLFhMfPSe%7C1NfhjFg9Yc4JxDU2kGX3kqxiNcfgtXjeDQ%7C1CBumw4oi3tNJgddfFghzAQv3Fv4QS2LvP%7C1JXc3hyMKDz3dbAAcVptqeY7LuwbAtQiL3%7C18C7QPUWDLT6wHhkeecfRUY3ccepTxy1ZQ%7C1N7VPACFfgMNQN8K1YD4DMVzLqo7RyaAq4%7C1LuNg3HhbwmJ5RP7VxPT9XrDJpYuGvxf7y%7C149adyrYTtgw7377uB3TJkuLZ8BfKzZdcP%7C1FC7fFo9a2rysxFympAGR6C6s4MY7CXAtA%7C1LMh5PUVG4yEXCs7tFs9UXceS6Umbdg54y%7C13JQxeQ5jmpSQ6EjznS3MFv1NzxJ5RFbKA%7C13ExP8mLdwFf3xzZ7NzyCtxkwgUdrnsU34%7C13TbNTLpz3ak7r7CdzMoFDVn31ymXfSw7U%7C1FLvpkUaUaizf6dzqbwAwK9PAVZocL2sxP%7C1JDN7fLTZBdjs4cgmBRWfchdmNDyh93Doh%7C1ABrpgsSAzpHpv5qZng3Nrdcf4a3LUQoet%7C14ipAEtXgqmnsMUj6F2RjK7K7YtVPjtCKe%7C1BafYqjB1HcHcdf5qgoQmMr2GzpqEqG2QA%7C1Bm3LzUKSC5JNTmWqa5LMxqekd4AGMjRmm%7C14Vh89KneTkaXxN6UhvLPRtLQScWQgKqEy%7C1GpNFqpP9j8BfjKYqTfbY8HkWWW5Ns6PRs%7C1CQJZm1RKHCKrg979WPPZUQdtpJeCJXJV2%7C1HyuG8gSC5fCutydsmZ5J5xcR9XYbBuv1r%7C1EafsFtngMQVfTvMnqeDKAREs94dKiAE6c%7C16iZQU1xW6eciY5PykDsvYHad39GH31r13%7C18XfusX9aAMYqmiW1NKuDzuLy2RbV1pux7%7C1MTnrEcPbPG93Pg3CSze6rNvzLkMRH77N9%7C1BmrrnwfNT1t496uyB7ppyVuiLrMX3PwxW%7C1RJsVu8NgjuagUgdzY3NkVBfuPvG5P5Ed%7C16Wc9QcYNRpmzGjAFBd6RFpFainRXByhqU%7C17wKJH6vaPCrAU1N1Uc3SiMSD9XNUqaLeb%7C18y4ed3uBDYqLwrotHBm3DYpM6dbhJUjsH%7C1MgFzNEF6GGTeCZzhvc4Zh1kCTrtHNTJZX%7C1PaoyxW8bUj25pAweDmMhBvoibLT2XjdMe%7C1L7uE74R8ooLJ26pVhXBUfbUPx7s4YGsnC%7C1PimqhZ1jnCUX36z8iQvBY5ukt1HGomgRj%7C16sSbuCVC1SmWnmo7eMGzzL8WTDmXpLZ5D%7C1fbsA53gXvHNCs2op6Cqih815uUjTwqvs%7C1Fheg4A3GWyA3cJUSK1iPbWQbQ22BmcsJe%7C18UwJMqZZ9jMKKqenjLU36HxkYCDxzhKc%7C1CDKvmwVtJpzNvD72YSEspvdUr7fUc8WcS%7C1Pxw1w1FJuoBrfLo6QFwA9LAQxerTUHj18%7C1BsPMAgBbhot1paQc4WiKkiHfyz2DEXZZN%7C1F1DbdbumRSrXoRUhMy7Pcjsf9MxNjYEj8%7C1Kx5BurqWd4GigzPqMJuZrb6Z52qx3E4gk%7C137NDACMuXzKa6itmaua6y6qc3c4NWgFUK%7C1G7nzUmH2wBqc7Py8HgtwPUn7kbeRWoR24%7C1N7xzt4GbSrbUKAFaCi7VKNGxmpb8g7Pwf%7C1JutDz3BP9Xi24SSJzgxW2hE7AR2mXL6vD%7C18CjAAXAFcBbJJqou9niS7uCr9bbQu2BSm%7C1K7Fts1W7V95MVAfgXRDmj98Aa1ZRAw8AU%7C1EFLEy4F5388bvUn6QWvgPnE5GrWVK2ef%7C1nZjd3R4rHAXdiptnPtLdeJdAdfp34RCb%7C1CAeqTj6zPqrPptEjcmtXjv2S9z5TtEbji%7C1HdVbXrsMzPw86ECsikwJPSofNJfrSU2eh%7C16F9GoBun9VrF2Qcvo1trzLRn7nMtdhUQN%7C12yp1d6UgPRDkz1i1BfugpZzBoKd9DCnX7%7C1EBngT4auPkvVebydgHr3B65NEKDqu4xWL%7C174kgguY1Fzm6pZS81gwQdWvfAMfDPcWLT%7C18njhypvU7qPoDEmzk87EDmJKEMunCmjQw%7C1PavTcuJzrtSgAoxrz1PcjSWGk4Z4nsreA%7C1ML8rws13EmvsapoKYCowSHuqz4kYtTeWH (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x75649760>: Failed to establish a new connection: [Errno -2] Name or service not known'))
```

**Comment by raphaelsander** [comment]
Fixed adding a exception in the connection.
